### ISSUE TITLE
errors, cant spawn

### ISSUE THREAD

**Issue by mamawolfie** [Sina30/NoPixelserver3.0#2]
![image](https://user-images.githubusercontent.com/79067758/147858192-505af429-1102-4e16-ace8-47f54ad4f5df.png)

**Comment by MrTraxx** [comment]
@mamawolfie we need a fix

**Comment by MrTraxx** [comment]
@Sina30  we need a fix

**Comment by Otacon-404** [comment]
if you can read the error you can fix it easily

**Comment by MrTraxx** [comment]
ye i fixed it already
